UPDATE public."Disease"
SET model_order = CASE
WHEN name = 'Drug Reaction' THEN 14
WHEN name = 'Malaria' THEN 29
WHEN name = 'Allergy' THEN 4
WHEN name = 'Hypothyroidism' THEN 26
WHEN name = 'Psoriasis' THEN 35
WHEN name = 'GERD' THEN 16
WHEN name = 'Chronic cholestasis' THEN 9
WHEN name = 'hepatitis A' THEN 40
WHEN name = 'Osteoarthristis' THEN 31
WHEN name = '(vertigo) Paroymsal  Positional Vertigo' THEN 0
WHEN name = 'Hypoglycemia' THEN 25
WHEN name = 'Acne' THEN 2
WHEN name = 'Diabetes' THEN 12
WHEN name = 'Impetigo' THEN 27
WHEN name = 'Hypertension' THEN 23
WHEN name = 'Peptic ulcer diseae' THEN 33
WHEN name = 'Dimorphic hemorrhoids(piles)' THEN 13
WHEN name = 'Common Cold' THEN 10
WHEN name = 'Chicken pox' THEN 8
WHEN name = 'Cervical spondylosis' THEN 7
WHEN name = 'Hyperthyroidism' THEN 24
WHEN name = 'Bronchial Asthma' THEN 6
WHEN name = 'Urinary tract infection' THEN 38
WHEN name = 'Varicose veins' THEN 39
WHEN name = 'AIDS' THEN 1
WHEN name = 'Paralysis (brain hemorrhage)' THEN 32
WHEN name = 'Typhoid' THEN 37
WHEN name = 'Hepatitis B' THEN 19
WHEN name = 'Fungal infection' THEN 15
WHEN name = 'Hepatitis C' THEN 20
WHEN name = 'Hepatitis D' THEN 21
WHEN name = 'Migraine' THEN 30
WHEN name = 'Alcoholic hepatitis' THEN 3
WHEN name = 'Jaundice' THEN 28
WHEN name = 'Hepatitis E' THEN 22
WHEN name = 'Dengue' THEN 11
WHEN name = 'Heart attack' THEN 18
WHEN name = 'Pneumonia' THEN 34
WHEN name = 'Arthritis' THEN 5
WHEN name = 'Gastroenteritis' THEN 17
WHEN name = 'Tuberculosis' THEN 36
END